<a href="https://colab.research.google.com/github/Prajwal-ak-0/3d/blob/master/Part_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Introduction to Machine Learning and Deep Learning

**Machine Learning (ML)**: A branch of AI that learns from data and predicts unseen data. It can be applied everywhere, as long as we are able to convert the data into numbers, program it, and find patterns.

### Differences between ML and DL
* **Machine Learning (ML)** is generally applied to structured data.
* **Deep Learning (DL)**, a subset of ML, is typically applied to unstructured data.

### When to Apply ML/DL
* When we cannot specify all the rules we are going to encounter and the environment keeps changing with time.
* When there is a large amount of data, we can use ML/DL to gain insights.

### When Not to Apply DL
* If we can solve the problem with simple ML, it is better to avoid DL as it requires more computation.
* In the absence of large data, ML is preferred to deliver accurate results.

![Machine Learning vs Deep Learning](https://assets-global.website-files.com/5fb24a974499e90dae242d98/60f6fcbbeb0b8f57a7980a98_5f213db7c7763a9288759ad1_5eac2d0ef117c236e34cc0ff_DeepLearning.jpeg)

# Artificial Neural Network (ANN)

**Artificial Neural Network (ANN)**: A model inspired by the structure and function of biological neural networks. It consists of:

1. **Input Layer**: The incoming data is fed into this layer. Generally, it is a single layer.
2. **Hidden Layer(s)**: The model can consist of any number of hidden layers. Each layer helps in feature extraction.
3. **Output Layer**: Based on the extracted features, this layer makes the final decision.




# 2. Tensorflow basics

**TensorFlow**: An end-to-end open-source machine learning platform used to develop models for various tasks, including natural language processing, image recognition, etc.

* Contains prebuilt models.
* Provides the tools to build or customize a model.


In [7]:
import tensorflow as tf

In [8]:
scalar = tf.constant(10)
scalar
print(scalar.ndim)

0


In [9]:
vector = tf.constant([10,20,30,40])
vector
print(vector.ndim)

1


In [10]:
matrix = tf.constant([[10,20,30,40], [40,50,60,80]])
matrix
print(matrix.ndim)

2


In [11]:
tensor = tf.constant([[[10,20,30],[40,50,60]], [[10,20,30],[40,50,60]], [[10,20,30],[40,50,60]], [[10,20,30],[40,50,60]]])
tensor
print(tensor.ndim)

3


### **constant()** vs **variable()**

In [12]:
var = tf.Variable([10,7])
const = tf.constant([10,7])
print(var)
print(const)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>
tf.Tensor([10  7], shape=(2,), dtype=int32)


In [13]:
var[0].assign(100)
print(var)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([100,   7], dtype=int32)>


In [14]:
# const[0].assign(100)

# NameError                                 Traceback (most recent call last)
# <ipython-input-3-f1af4f6e9736> in <cell line: 1>()
# ----> 1 const[0].assign(100)

# NameError: name 'const' is not defined

### Creating Random Tensors

In [31]:
rand_1 = tf.random.Generator.from_seed(40)
rand_1 = rand_1.normal(shape=(3,4))
rand_2 = tf.random.Generator.from_seed(40)
rand_2 = rand_2.normal(shape=(3,4))

rand_1, rand_2, rand_1 == rand_2

(<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[ 0.78953624,  0.53897345, -0.48535708,  0.74055266],
        [ 0.31662667, -1.4391748 ,  0.58923835, -1.4268045 ],
        [-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ]],
       dtype=float32)>,
 <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[ 0.78953624,  0.53897345, -0.48535708,  0.74055266],
        [ 0.31662667, -1.4391748 ,  0.58923835, -1.4268045 ],
        [-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ]],
       dtype=float32)>,
 <tf.Tensor: shape=(3, 4), dtype=bool, numpy=
 array([[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])>)

In [32]:
rand_1 = tf.random.Generator.from_seed(40)
rand_1 = rand_1.normal(shape=(3,4))
rand_2 = tf.random.Generator.from_seed(10)
rand_2 = rand_2.normal(shape=(3,4))

rand_1, rand_2, rand_1 == rand_2

(<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[ 0.78953624,  0.53897345, -0.48535708,  0.74055266],
        [ 0.31662667, -1.4391748 ,  0.58923835, -1.4268045 ],
        [-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ]],
       dtype=float32)>,
 <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[-0.29604465, -0.21134205,  0.01063002,  1.5165398 ],
        [ 0.27305737, -0.29925638, -0.3652325 ,  0.61883307],
        [-1.0130816 ,  0.28291714,  1.2132233 ,  0.46988967]],
       dtype=float32)>,
 <tf.Tensor: shape=(3, 4), dtype=bool, numpy=
 array([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])>)

### Shuffling the order of the tensors

In [46]:
shuffle = tf.constant([[10,2,3], [32,34,5], [12,43,23], [22,1,21]])
tf.random.shuffle(shuffle, seed=10)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[10,  2,  3],
       [22,  1, 21],
       [32, 34,  5],
       [12, 43, 23]], dtype=int32)>

In [47]:
shuffle = tf.constant([[10,2,3], [32,34,5], [12,43,23], [22,1,21]])
tf.random.shuffle(shuffle, seed = 10)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[12, 43, 23],
       [32, 34,  5],
       [22,  1, 21],
       [10,  2,  3]], dtype=int32)>

### Setting A Global Seed

In [55]:
shuffle = tf.constant([[10,2,3], [32,34,5], [12,43,23], [22,1,21]])
tf.random.set_seed(10)
tf.random.shuffle(shuffle)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[12, 43, 23],
       [22,  1, 21],
       [10,  2,  3],
       [32, 34,  5]], dtype=int32)>

### Creating A Tensor From Numpy

In [69]:
import numpy as np
numpy_A = np.arange(1, 25)
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int64, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

### Shape, Rank and Size

In [72]:
# Creating a 4 dimension tensor
random_4_T = tf.zeros(shape=(2,3,4,5))
random_4_T

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [85]:
print("Data type of tensor : ",random_4_T.shape)
print("Dimension(rank) of a tensor : ",random_4_T.ndim)
print("Datatype of tensor : ", random_4_T.dtype)
print("Total No of element in tensor : ",tf.size(random_4_T).numpy())
print("No of ele along 0th dim : ", random_4_T.shape[0])
print("No of ele along last dim : ", random_4_T.shape[-1])

Data type of tensor :  (2, 3, 4, 5)
Dimension(rank) of a tensor :  4
Datatype of tensor :  <dtype: 'float32'>
Total No of element in tensor :  120
No of ele along 0th dim :  2
No of ele along last dim :  5
